### ISSUE TITLE
Wrong url for Linux

### ISSUE THREAD

**Issue by MaestroJurko** [zeevl/phantomjs2#10]
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2 - 404

**Comment by ghost** [comment]
+1 same (not just with phantomjs2, but with the official Medium release and others - what is going on?)

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.0.0-linux-x86_64.tar.bz2
Receiving...

Error requesting archive.
Status: 404
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie, Accept-Encoding",
  "cache-control": "max-age=900",
  "content-type": "text/html; charset=utf-8",
  "strict-transport-security": "max-age=31536000",
  "date": "Sun, 10 Jan 2016 16:44:24 GMT",
  "x-served-by": "app-107",
  "content-language": "en",
  "etag": "\"08f04c80c4768fa2b01ad2a0f88bead0\"",
  "x-static-version": "20ccbc52706b",
  "x-render-time": "0.0308151245117",
  "connection": "close",
  "x-request-count": "283",
  "x-frame-options": "SAMEORIGIN",
  "x-version": "20ccbc52706b",
  "content-length": "23998"
}
Make sure your network and proxy settings are correct.

**Comment by pfitzpaddy** [comment]
+1

**Comment by monkpit** [comment]
It 404's because there is no static file for Linux hosted on ariya/phantomjs anymore - binaries are only distributed for PhantomJS 2 for Windows and Mac.

However, this package's readme says that the files are fetched from https://github.com/bprodoehl/phantomjs/releases/ (which apparently they are not).

And if you check there, you will find builds for 2.0.0 that work nicely.

`npm install phantomjs2 --phantomjs_downloadurl=https://github.com/bprodoehl/phantomjs/releases/download/v2.0.0-20150528/phantomjs-2.0.0-20150528-u1504-x86_64.zip`

Works fine for me on an ubuntu-based distro.

**Comment by drom** [comment]
yes, I got the same error.

**Comment by hmdhk** [comment]
Now linux binaries are available:
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-i686.tar.bz2
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2

but still tries to download a dead link:
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2

**Comment by zeevl** [comment]
Fixed with https://github.com/zeevl/phantomjs2/pull/13
